App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views.index import *
from .views.sport import *
from .views.schedules import *
from .views.company import *
from .views.spaces import *
from .views.reservation import *
from .views.users import *
from .views.roles import *
from .views.login import *
from .views.logs import *
from django.conf.urls import handler404
from django.contrib.auth import views as auth_views

handler404 = Custom404View.as_view()

urlpatterns = [
    #Login
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    #Home
    path('home/', CustomIndexView.as_view(), name="home"),
    #Sport
    path('sport/', ListSportView.as_view(), name="sport_list"),
    path('sport/create/', CreateSportView.as_view(), name="sport_create"),
    path('sport/update/<int:pk>/', UpdateSportView.as_view(), name="sport_update"),
    path('sport/delete/<int:pk>/', DeleteSportView.as_view(), name="sport_delete"),
    #Schedules
    path('schedules/', ListScheduleView.as_view(), name="schedules_list"),
    path('schedules/create/', CreateScheduleView.as_view(), name="schedules_create"),
    path('schedules/update/<int:pk>/', UpdateScheduleView.as_view(), name="schedules_update"),
    path('schedules/delete/<int:pk>/', DeleteScheduleView.as_view(), name="schedules_delete"),
    #Company
    path('company/create/', CreateCompanyView.as_view(), name="company_create"),
    path('company/update/<int:pk>/', UpdateCompanyView.as_view(), name="company_update"),
    #Spaces
    path('spaces/', ListSpacesView.as_view(), name="spaces_list"),
    path('spaces/create/', CreateSpacesView.as_view(), name="spaces_create"),
    path('spaces/update/<int:pk>/', UpdateSpacesView.as_view(), name="spaces_update"),
    path('spaces/delete/<int:pk>/', DeleteSpacesView.as_view(), name="spaces_delete"),
    path('spaces/ajax/<int:pk>/', AjaxSpacesByIdView.as_view(), name="spaces_ajax"),
    #Reservation
    path('reservation/', ListReservationView.as_view(), name="reservation_list"),
    path('calendar/', CalendarReservationView.as_view(), name="calendar"),
    path('reservations/', ReservationEventsView.as_view(), name="reservations_events"),
    path('reservation/create/', CreateReservationView.as_view(), name="reservation_create"),
    path('reservation/update/<int:pk>/', UpdateReservationView.as_view(), name="reservation_update"),
    path('reservation/delete/<int:pk>/', DeleteReservationView.as_view(), name="reservation_delete"),
    #Users
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('users/<int:pk>/permissions/', UserPermissionUpdateView.as_view(), name='user_permissions'),
    path('user/recover/password/', Recoverpassword.as_view(), name='recovery_password'),
    path('reset/<uidb64>/<token>/',CustomPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    #Roles
    path('roles/', RoleListView.as_view(), name='role_list'),
    path('roles/create/', RoleCreateView.as_view(), name='role_create'),
    path('roles/<int:pk>/update/', RoleUpdateView.as_view(), name='role_update'),
    path('roles/<int:pk>/delete/', RoleDeleteView.as_view(), name='role_delete'),
    #Logs
    path('logs/', LogsListView.as_view(), name='logs_list'),

]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

appZona3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

App/models.py
from django.db import models
from enum import Enum
from django.contrib.auth.models import Permission
from django.contrib.auth import get_user_model

User = get_user_model()

class Sport(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True, max_length=1000)

    class Meta:
        verbose_name = 'Sport'
        verbose_name_plural = 'Sports'
        db_table = 'sport'
        default_permissions = ()

    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=15)
    description = models.TextField(null=True, blank=True)
    logo = models.ImageField(upload_to='company_logo/', null=True, blank=True)

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'
        db_table = 'company'
        default_permissions = ()

    def __str__(self):
        return self.name

class Days(Enum):
    LUNES = 1
    MARTES = 2
    MIERCOLES = 3
    JUEVES = 4
    VIERNES = 5
    SABADO = 6
    DOMINGO = 7

    @classmethod
    def choices(cls):
        return [(tag.value, tag.name.capitalize()) for tag in cls]

class Schedule(models.Model):
    day = models.IntegerField(choices=Days.choices(), default=Days.LUNES.value)
    startime = models.TimeField()
    endtime = models.TimeField()

    class Meta:
        verbose_name = 'Schedule'
        verbose_name_plural = 'Schedules'
        db_table = 'schedules'
        default_permissions = ()

    def __str__(self):
        return f"{Days(self.day).name} ({self.startime} - {self.endtime})"

    @property
    def day_name(self):
        return Days(self.day).name.capitalize()

    
class Spaces(models.Model):
    name = models.CharField(max_length=50)
    sport = models.ForeignKey(Sport, on_delete=models.PROTECT)
    description = models.TextField(null=True, blank=True)
    schedule = models.ManyToManyField(Schedule, blank=True)
    numberplayers = models.IntegerField()

    class Meta:
        verbose_name = 'Space'
        verbose_name_plural = 'Spaces'
        db_table = 'spaces'
        default_permissions = ()

    def __str__(self):
        return self.name

class Reservation(models.Model):
    client_name = models.CharField(max_length=50)
    client_cell = models.CharField(max_length=15)
    client_email = models.EmailField()
    space = models.ForeignKey(Spaces, on_delete=models.PROTECT)
    reservation_start = models.DateTimeField()
    reservation_end = models.DateTimeField()

    class Meta:
        verbose_name = 'Reservation'
        verbose_name_plural = 'Reservations'
        db_table = 'reservation'
        default_permissions = ()

    def __str__(self):
        return self.client_name

class Module(models.Model):
    name = models.CharField(max_length=100, unique=True)
    icon = models.CharField(max_length=50)
    permissions = models.ManyToManyField(Permission, related_name='modules')
    url_name = models.CharField(max_length=100) 

    class Meta:
        default_permissions = ()

    def __str__(self):
        return self.name

    def user_has_access(self, user):
        return user.user_permissions.filter(id__in=self.permissions.values_list('id', flat=True)).exists()



class Log(models.Model):
    ACTION_CHOICES = [
        ('create', 'Create'),
        ('update', 'Update'),
        ('delete', 'Delete'),
    ]

    module = models.CharField(max_length=255)  
    date = models.DateTimeField(auto_now_add=True)  
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)  
    description = models.TextField()  
    action = models.CharField(max_length=10, choices=ACTION_CHOICES) 

    def __str__(self):
        return f"{self.module} - {self.action} - {self.date.strftime('%Y-%m-%d %H:%M:%S')}"

App/forms/reservation.py
from datetime import datetime
from zoneinfo import ZoneInfo
from django import forms
from App.models import Reservation

class ReservationForm(forms.ModelForm):

    class Meta:
        model = Reservation
        fields = ['client_name', 'client_cell', 'client_email', 'space', 'reservation_start', 'reservation_end']
        widgets = {
            'client_name': forms.TextInput(attrs={'class': 'form-control input-full'}),
            'client_cell': forms.NumberInput(attrs={
                'class': 'form-control input-full',
                'min': '0',
                'oninput': "this.value = Math.max(this.value, 0)"
            }),
            'client_email': forms.EmailInput(attrs={'class': 'form-control input-full'}),
            'space': forms.Select(attrs={'class': 'form-control input-full'}),
            'reservation_start': forms.DateTimeInput(attrs={'class': 'form-control datetimepicker'}),
            'reservation_end': forms.DateTimeInput(attrs={'class': 'form-control datetimepicker'}),
        }
    
    def clean(self):
        cleaned_data = super().clean()
        reservation_start = cleaned_data.get('reservation_start')
        reservation_end = cleaned_data.get('reservation_end')
        space = cleaned_data.get('space')
        overlapping_reservations = Reservation.objects.filter(space=space).exclude(id=self.instance.id)
        
        for reservation in overlapping_reservations:
            if (reservation_start <= reservation.reservation_start < reservation_end) or (reservation_start < reservation.reservation_end <= reservation_end) or (reservation_start <= reservation.reservation_start and reservation_end >= reservation.reservation_end):
                self.add_error('reservation_start', f"Esta reserva se cruza con otra.")
                self.add_error('reservation_end', f"Esta reserva se cruza con otra.")
        
        if reservation_start and reservation_end and reservation_start >= reservation_end:
            self.add_error('reservation_start', "La fecha de inicio debe ser menor que la fecha de fin.")
            self.add_error('reservation_end', "La fecha de fin debe ser mayor que la fecha de inicio.")

        timezone = ZoneInfo('America/Bogota')
        date_now = datetime.now(timezone)
        if reservation_start and reservation_start < date_now:
            self.add_error('reservation_start', "La fecha de inicio debe ser mayor que la fecha actual.")

        return cleaned_data

App/views/reservation.py
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import *
from django.contrib import messages  
from App.models import Reservation
from App.forms import ReservationForm
from django.http import JsonResponse

class ListReservationView(ListView):
    model = Reservation
    template_name = "reservation/list.html"
    context_object_name = "reservations"

class CalendarReservationView(ListView):
    model = Reservation
    template_name = "reservation/calendar.html"
    context_object_name = "reservations"

class ReservationEventsView(View):
    def get(self, request, *args, **kwargs):
        reservations = Reservation.objects.all()
        events = []
        for r in reservations:
            events.append({
                "id": r.id,
                "title": u'{} - {}'.format(r.client_name, r.space.name ),
                "start": r.reservation_start.isoformat(),
                "end": r.reservation_end.isoformat(),
                "extendedProps": {
                    "client_name": r.client_name,
                    "client_cell": r.client_cell,
                    "client_email": r.client_email,
                    "space": r.space.name if r.space else '',
                }
            })
        return JsonResponse(events, safe=False)

    
class CreateReservationView(SuccessMessageMixin, CreateView):
    model = Reservation
    form_class = ReservationForm
    template_name = "reservation/create.html"
    success_url = reverse_lazy('reservation_list')
    success_message = "Reserva creada correctamente"

class UpdateReservationView(SuccessMessageMixin, UpdateView):
    model = Reservation
    form_class = ReservationForm
    template_name = "reservation/edit.html"
    success_url = reverse_lazy('reservation_list')
    success_message = "Reserva modificada correctamente"

class DeleteReservationView(DeleteView):
    model = Reservation
    template_name = "reservation/delete.html"
    success_url = reverse_lazy('reservation_list')

    def form_valid(self, form):
        messages.success(self.request, "Reserva eliminada correctamente")
        return super().form_valid(form)

App/templates/reservation/calendar.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
 <link rel="stylesheet" href="{% static 'css/styles_calendar.css' %}" />
{% endblock %}

{% block contenido %}
<div class="page-inner">
  <div class="col-md-12">
    <div id='calendar'></div>
  </div>
</div>
<div class="modal fade" id="reservationModal" tabindex="-1" aria-labelledby="reservationModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="reservationModalLabel">Detalles de la Reserva</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
      </div>
      <div class="modal-body">
        <p><strong>Cliente:</strong> <span id="clientName"></span></p>
        <p><strong>Celular:</strong> <span id="clientCell"></span></p>
        <p><strong>Email:</strong> <span id="clientEmail"></span></p>
        <p><strong>Espacio:</strong> <span id="spaceName"></span></p>
        <p><strong>Inicio:</strong> <span id="reservationStart"></span></p>
        <p><strong>Fin:</strong> <span id="reservationEnd"></span></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
  <script src="{% static 'js/app/tools.js' %}"></script>
  <script src="{% static 'js/plugin/full-calendar/full-calendar.min.js' %}"></script>
 <script src="{% static 'js/app/calendar.js' %}"></script>

{% endblock %}

App/templates/reservation/create.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
<form method="post" id="reservation-form" novalidate>
    {% csrf_token %}
    <div class="page-inner">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <div class="card-title">Crear Reserva</div>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="form-group form-inline">
                        <div class="row p-0">
                            <h4>Datos del cliente</h4><hr>
                            <div class="row p-0">
                                <div class="col-md-4">
                                    <div class="form-group {% if form.client_name.errors %}has-error has-feedback{% endif %}">
                                        <span for="inlineinput" class="col-form-label">Nombre</span>
                                        {{ form.client_name }}
                                        <label>{{ form.client_name.errors }}</label>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group {% if form.client_cell.errors %}has-error has-feedback{% endif %}">
                                        <span for="inlineinput" class="col-form-label">Numero celular</span>
                                        {{ form.client_cell }}
                                        <label>{{ form.client_cell.errors }}</label>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group {% if form.client_email.errors %}has-error has-feedback{% endif %}">
                                        <span for="inlineinput" class="col-form-label">Correo electronico</span>
                                        {{ form.client_email }}
                                        <label>{{ form.client_email.errors }}</label>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <h4>Datos de la reserva</h4><hr>
                            <div class="row p-0">
                                <div class="col-md-4">
                                    <div class="form-group {% if form.space.errors %}has-error has-feedback{% endif %}">
                                        <span for="inlineinput" class="col-md-6 col-form-label">Espacio</span>
                                        {{ form.space }}
                                        <label>{{ form.space.errors }}</label>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group {% if form.reservation_start.errors %}has-error has-feedback{% endif %}">
                                        <label for="id_reservation_start" class="form-label">Fecha y hora de inicio</label>
                                        <div class="input-group">
                                            {{ form.reservation_start }}
                                            <button type="button" id="clear-start" class="btn btn-outline-secondary">✖</button>
                                        </div>
                                        <label>{{ form.reservation_start.errors }}</label>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group {% if form.reservation_end.errors %}has-error has-feedback{% endif %}">
                                        <label for="id_reservation_end" class="form-label">Fecha y hora fin</label>
                                        <div class="input-group">
                                            {{ form.reservation_end }}
                                            <button type="button" id="clear-end" class="btn btn-outline-secondary">✖</button>
                                        </div>
                                        <label>{{ form.reservation_end.errors }}</label>
                                    </div>
                                </div>
                            </div>  
                        </div>
                    </div>
                </div>
              </div>
            </div>
            <div class="card-action d-flex justify-content-end">
                <a href="{% url 'reservation_list' %}" class="btn btn-danger">Cancelar</a>
                <button type="submit" class="btn btn-success ms-2">Guardar</button>
            </div>
          </div>
        </div>
      </div>
    </div>
</form>
{% endblock %}
{% block scripts %}
  <script src="{% static 'js/app/reservation.js' %}"></script>
{% endblock %}

App/templates/reservation/delete.html
{% extends "base.html" %}
{% block contenido %}
<form method="post">
    {% csrf_token %}
    <div class="page-inner">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <div class="card-title">Eliminar reserva</div>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-lg-12">
                    <p>¿Está seguro de eliminar la reserva <b>{{ reservation.client_name }}</b>?</p>
                </div>
              </div>
            </div>
            <div class="card-action d-flex justify-content-end">
              <a href="{% url 'reservation_list' %}" class="btn btn-info">Cancelar</a>
              <button type="submit" class="btn btn-danger ms-2">Eliminar</button>
            </div>
          </div>
        </div>
      </div>
    </div>
</form>
{% endblock %}

App/templates/reservation/edit.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
<form method="post" id="reservation-form" novalidate>
    {% csrf_token %}
    <div class="page-inner">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <div class="card-title">Editar Reserva</div>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="form-group form-inline">
                        <div class="row p-0">
                            <h4>Datos del cliente</h4><hr>
                            <div class="row p-0">
                                <div class="col-md-4">
                                    <div class="form-group {% if form.client_name.errors %}has-error has-feedback{% endif %}">
                                        <span for="inlineinput" class="col-form-label">Nombre</span>
                                        {{ form.client_name }}
                                        <label>{{ form.client_name.errors }}</label>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group {% if form.client_cell.errors %}has-error has-feedback{% endif %}">
                                        <span for="inlineinput" class="col-form-label">Numero celular</span>
                                        {{ form.client_cell }}
                                        <label>{{ form.client_cell.errors }}</label>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group {% if form.client_email.errors %}has-error has-feedback{% endif %}">
                                        <span for="inlineinput" class="col-form-label">Correo electronico</span>
                                        {{ form.client_email }}
                                        <label>{{ form.client_email.errors }}</label>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <h4>Datos de la reserva</h4><hr>
                            <div class="row p-0">
                                <div class="col-md-4">
                                    <div class="form-group {% if form.space.errors %}has-error has-feedback{% endif %}">
                                        <span for="inlineinput" class="col-md-6 col-form-label">Espacio</span>
                                        {{ form.space }}
                                        <label>{{ form.space.errors }}</label>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group {% if form.reservation_start.errors %}has-error has-feedback{% endif %}">
                                        <label for="id_reservation_start" class="form-label">Fecha y hora de inicio</label>
                                        <div class="input-group">
                                            {{ form.reservation_start }}
                                            <button type="button" id="clear-start" class="btn btn-outline-secondary">✖</button>
                                        </div>
                                        <label>{{ form.reservation_start.errors }}</label>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group {% if form.reservation_end.errors %}has-error has-feedback{% endif %}">
                                        <label for="id_reservation_end" class="form-label">Fecha y hora fin</label>
                                        <div class="input-group">
                                            {{ form.reservation_end }}
                                            <button type="button" id="clear-end" class="btn btn-outline-secondary">✖</button>
                                        </div>
                                        <label>{{ form.reservation_end.errors }}</label>
                                    </div>
                                </div>
                            </div>  
                        </div>
                    </div>
                </div>
              </div>
            </div>
            <div class="card-action d-flex justify-content-end">
                <a href="{% url 'reservation_list' %}" class="btn btn-danger">Cancelar</a>
                <button type="submit" class="btn btn-success ms-2">Guardar</button>
            </div>
          </div>
        </div>
      </div>
    </div>
</form>
{% endblock %}
{% block scripts %}
  <script src="{% static 'js/app/reservation.js' %}"></script>
{% endblock %}

App/templates/reservation/list.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
    <div class="page-inner">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <div class="row align-items-center">
                <div class="col-12 col-md-10">
                    <h4 class="card-title">Reservas</h4>
                </div>
                <div class="col-12 col-md-12 text-md-end text-center mt-2 mt-md-0">
                    <a href="{% url 'reservation_create' %}" class="btn btn-secondary">
                        <span class="btn-label">
                            <i class="fa fa-plus"></i>
                        </span>
                        Crear Reserva
                    </a>
                    <a href="{% url 'calendar' %}" class="btn btn-secondary">
                        <span class="btn-label">
                            <i class="fa fa-calendar"></i>
                        </span>
                        Calendario
                    </a>
                </div>
            
            </div>
        </div> 
          <div class="card-body">
            <div class="table-responsive">
              <table id="multi-filter-select" class="display table table-striped table-hover">
                <thead>
                  <tr>
                    <th class="text-center">Id</th>
                    <th class="text-center">Datos del cliente</th>
                    <th class="text-center">Espacio</th>
                    <th class="text-center">Hora de inicio</th>
                    <th class="text-center">Hora fin</th>
                    <th class="text-center">Gestión</th>
                  </tr>
                </thead>
                <tbody>
                    {% for reservation in reservations %}
                  <tr>
                    <td class="text-center">{{ reservation.id }}</td>
                    <td class="text-center">{{ reservation.client_name }}</td>
                    <td class="text-center">{{ reservation.space }}</td>
                    <td class="text-center">{{ reservation.reservation_start|date:"j \d\e F \d\e Y \- g:i a" }}</td>    
                    <td class="text-center">{{ reservation.reservation_end|date:"j \d\e F \d\e Y \- g:i a" }}</td>
                    <td class="text-center">
                        <div class="d-flex justify-content-center gap-2">
                            <a href="{% url 'reservation_update' reservation.id %}" 
                               class="btn btn-icon btn-round btn-black btn-secondary"
                               data-bs-toggle="tooltip" 
                               data-bs-placement="top" 
                               title="Editar reserva">
                                <i class="fa fa-edit"></i>
                            </a>
                            
                            <a href="{% url 'reservation_delete' reservation.id %}" 
                               class="btn btn-icon btn-round btn-black btn-danger"
                               data-bs-toggle="tooltip" 
                               data-bs-placement="top" 
                               title="Eliminar reserva">
                                <i class="fa fa-trash"></i>
                            </a>
                        </div>
                    </td>                                      
                  </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
  </div>
{% endblock %}
{% block scripts %}
  <script src="{% static 'js/app/tools.js' %}"></script>
{% endblock %}