App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views.index import *
from .views.sport import *
from .views.schedules import *
from .views.company import *
from .views.spaces import *
from .views.reservation import *
from .views.users import *
from .views.roles import *
from .views.login import *
from .views.logs import *
from django.conf.urls import handler404
from django.contrib.auth import views as auth_views

handler404 = Custom404View.as_view()

urlpatterns = [
    #Login
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    #Home
    path('home/', CustomIndexView.as_view(), name="home"),
    #Sport
    path('sport/', ListSportView.as_view(), name="sport_list"),
    path('sport/create/', CreateSportView.as_view(), name="sport_create"),
    path('sport/update/<int:pk>/', UpdateSportView.as_view(), name="sport_update"),
    path('sport/delete/<int:pk>/', DeleteSportView.as_view(), name="sport_delete"),
    #Schedules
    path('schedules/', ListScheduleView.as_view(), name="schedules_list"),
    path('schedules/create/', CreateScheduleView.as_view(), name="schedules_create"),
    path('schedules/update/<int:pk>/', UpdateScheduleView.as_view(), name="schedules_update"),
    path('schedules/delete/<int:pk>/', DeleteScheduleView.as_view(), name="schedules_delete"),
    #Company
    path('company/create/', CreateCompanyView.as_view(), name="company_create"),
    path('company/update/<int:pk>/', UpdateCompanyView.as_view(), name="company_update"),
    #Spaces
    path('spaces/', ListSpacesView.as_view(), name="spaces_list"),
    path('spaces/create/', CreateSpacesView.as_view(), name="spaces_create"),
    path('spaces/update/<int:pk>/', UpdateSpacesView.as_view(), name="spaces_update"),
    path('spaces/delete/<int:pk>/', DeleteSpacesView.as_view(), name="spaces_delete"),
    path('spaces/ajax/<int:pk>/', AjaxSpacesByIdView.as_view(), name="spaces_ajax"),
    #Reservation
    path('reservation/', ListReservationView.as_view(), name="reservation_list"),
    path('calendar/', CalendarReservationView.as_view(), name="calendar"),
    path('reservations/', ReservationEventsView.as_view(), name="reservations_events"),
    path('reservation/create/', CreateReservationView.as_view(), name="reservation_create"),
    path('reservation/update/<int:pk>/', UpdateReservationView.as_view(), name="reservation_update"),
    path('reservation/delete/<int:pk>/', DeleteReservationView.as_view(), name="reservation_delete"),
    #Users
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('users/<int:pk>/permissions/', UserPermissionUpdateView.as_view(), name='user_permissions'),
    path('user/recover/password/', Recoverpassword.as_view(), name='recovery_password'),
    path('reset/<uidb64>/<token>/',CustomPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    #Roles
    path('roles/', RoleListView.as_view(), name='role_list'),
    path('roles/create/', RoleCreateView.as_view(), name='role_create'),
    path('roles/<int:pk>/update/', RoleUpdateView.as_view(), name='role_update'),
    path('roles/<int:pk>/delete/', RoleDeleteView.as_view(), name='role_delete'),
    #Logs
    path('logs/', LogsListView.as_view(), name='logs_list'),

]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

appZona3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

App/models.py
from django.db import models
from enum import Enum
from django.contrib.auth.models import Permission
from django.contrib.auth import get_user_model

User = get_user_model()

class Sport(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True, max_length=1000)

    class Meta:
        verbose_name = 'Sport'
        verbose_name_plural = 'Sports'
        db_table = 'sport'
        default_permissions = ()

    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=15)
    description = models.TextField(null=True, blank=True)
    logo = models.ImageField(upload_to='company_logo/', null=True, blank=True)

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'
        db_table = 'company'
        default_permissions = ()

    def __str__(self):
        return self.name

class Days(Enum):
    LUNES = 1
    MARTES = 2
    MIERCOLES = 3
    JUEVES = 4
    VIERNES = 5
    SABADO = 6
    DOMINGO = 7

    @classmethod
    def choices(cls):
        return [(tag.value, tag.name.capitalize()) for tag in cls]

class Schedule(models.Model):
    day = models.IntegerField(choices=Days.choices(), default=Days.LUNES.value)
    startime = models.TimeField()
    endtime = models.TimeField()

    class Meta:
        verbose_name = 'Schedule'
        verbose_name_plural = 'Schedules'
        db_table = 'schedules'
        default_permissions = ()

    def __str__(self):
        return f"{Days(self.day).name} ({self.startime} - {self.endtime})"

    @property
    def day_name(self):
        return Days(self.day).name.capitalize()

    
class Spaces(models.Model):
    name = models.CharField(max_length=50)
    sport = models.ForeignKey(Sport, on_delete=models.PROTECT)
    description = models.TextField(null=True, blank=True)
    schedule = models.ManyToManyField(Schedule, blank=True)
    numberplayers = models.IntegerField()

    class Meta:
        verbose_name = 'Space'
        verbose_name_plural = 'Spaces'
        db_table = 'spaces'
        default_permissions = ()

    def __str__(self):
        return self.name

class Reservation(models.Model):
    client_name = models.CharField(max_length=50)
    client_cell = models.CharField(max_length=15)
    client_email = models.EmailField()
    space = models.ForeignKey(Spaces, on_delete=models.PROTECT)
    reservation_start = models.DateTimeField()
    reservation_end = models.DateTimeField()

    class Meta:
        verbose_name = 'Reservation'
        verbose_name_plural = 'Reservations'
        db_table = 'reservation'
        default_permissions = ()

    def __str__(self):
        return self.client_name

class Module(models.Model):
    name = models.CharField(max_length=100, unique=True)
    icon = models.CharField(max_length=50)
    permissions = models.ManyToManyField(Permission, related_name='modules')
    url_name = models.CharField(max_length=100) 

    class Meta:
        default_permissions = ()

    def __str__(self):
        return self.name

    def user_has_access(self, user):
        return user.user_permissions.filter(id__in=self.permissions.values_list('id', flat=True)).exists()



class Log(models.Model):
    ACTION_CHOICES = [
        ('create', 'Create'),
        ('update', 'Update'),
        ('delete', 'Delete'),
    ]

    module = models.CharField(max_length=255)  
    date = models.DateTimeField(auto_now_add=True)  
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)  
    description = models.TextField()  
    action = models.CharField(max_length=10, choices=ACTION_CHOICES) 

    def __str__(self):
        return f"{self.module} - {self.action} - {self.date.strftime('%Y-%m-%d %H:%M:%S')}"

App/forms/spaces.py
from django import forms
from App.models import Spaces, Schedule

class SpacesForm(forms.ModelForm):

    class Meta:
        model = Spaces
        fields = ['name', 'sport', 'description', 'schedule', 'numberplayers']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control input-full'}),
            'sport': forms.Select(attrs={'class': 'form-control input-full'}),
            'description': forms.Textarea(attrs={'class': 'form-control input-full'}),
            'numberplayers': forms.NumberInput(attrs={
                'class': 'form-control input-full',
                'min': '1',
                'oninput': "this.value = Math.max(this.value, 0)"
            })
        }

    schedule = forms.ModelMultipleChoiceField(
        queryset=Schedule.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control input-full style-select2'})
    )

App/views/spaces.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.db.models import Prefetch
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import *
from django.contrib import messages  
from App.models import Spaces, Schedule
from App.forms import SpacesForm

class ListSpacesView(ListView):
    model = Spaces
    template_name = "spaces/list.html"
    context_object_name = "spaces"

    def get_queryset(self):
        return Spaces.objects.prefetch_related(
            Prefetch('schedule', queryset=Schedule.objects.all().order_by('day', 'startime'))
        )

class CreateSpacesView(SuccessMessageMixin, CreateView):
    model = Spaces
    form_class = SpacesForm
    template_name = "spaces/create.html"
    success_url = reverse_lazy('spaces_list')
    success_message = "Espacio creado correctamente"

class UpdateSpacesView(SuccessMessageMixin, UpdateView):
    model = Spaces
    form_class = SpacesForm
    template_name = "spaces/edit.html"
    success_url = reverse_lazy('spaces_list')
    success_message = "Espacio editado correctamente"

class DeleteSpacesView(DeleteView):
    model = Spaces
    template_name = "spaces/delete.html"
    success_url = reverse_lazy('spaces_list')

    def form_valid(self, form):
        messages.success(self.request, "Espacio eliminado correctamente")
        return super().form_valid(form)
    

class AjaxSpacesByIdView(View):
    def get(self, request, pk):
        space = get_object_or_404(Spaces, pk=pk)
        data = [
                {
                    'id': schedule.pk,
                    'day': schedule.day,
                    'start_time': schedule.startime.strftime("%H:%M"),
                    'end_time': schedule.endtime.strftime("%H:%M")
                }
                for schedule in space.schedule.all()
            ]
        return JsonResponse({'data':data})

App/templates/spaces/create.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/base.css' %}" />
{% endblock %}
{% block contenido %}
<form method="post" novalidate>
    {% csrf_token %}
    <div class="page-inner">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <div class="card-title">Crear Espacio</div>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="form-group form-inline">
                        <div class="row p-0">
                            <div class="col-12"> 
                              <div class="row">
                                <div class="col-md-6">
                                  <div class="form-group {% if form.name.errors %}has-error has-feedback{% endif %}">
                                    <span for="inlineinput" class="col-md-6 col-form-label">Nombre</span>
                                    {{ form.name }}
                                    <label>{{ form.name.errors }}</label>
                                  </div>
                                </div>
                                <div class="col-md-6">
                                  <div class="form-group {% if form.sport.errors %}has-error has-feedback{% endif %}">
                                    <span for="inlineinput" class="col-md-6 col-form-label">Deporte</span>
                                    {{ form.sport }}
                                    <label> {{ form.sport.errors }} </label>
                                  </div>  
                                </div>
                              </div>
                              <div class="row">
                                <div class="col-md-6">
                                  <div class="form-group {% if form.numberplayers.errors %}has-error has-feedback{% endif %}">
                                    <span for="inlineinput" class="col-md-6 col-form-label">Numero de jugadores permitidos</span>
                                    {{ form.numberplayers }}
                                    <label> {{ form.numberplayers.errors }} </label>
                                  </div> 
                                </div>
                                <div class="col-md-6">
                                  <div class="form-group {% if form.schedule.errors %}has-error has-feedback{% endif %}">
                                    <span for="inlineinput" class="col-md-6 col-form-label">Horario de juego</span>
                                    {{ form.schedule }}
                                    <label> {{ form.schedule.errors }} </label>
                                  </div>
                                </div>
                              </div>
                              <div class="form-group">
                                <span for="inlineinput" class="col-md-6 col-form-label">Descripcion</span>
                                {{ form.description }}
                                <label> {{ form.description.errors }} </label>
                              </div>
                            </div>
                        </div>
                      </div>
                </div>
              </div>
            </div>
            <div class="card-action d-flex justify-content-end">
              <a href="{% url 'spaces_list' %}" class="btn btn-danger">Cancelar</a>
              <button type="submit" class="btn btn-success ms-2">Guardar</button>
            </div>
          </div>
        </div>
      </div>
    </div>
</form>
{% endblock %}

App/templates/spaces/delete.html
{% extends "base.html" %}
{% block contenido %}
<form method="post">
    {% csrf_token %}
    <div class="page-inner">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <div class="card-title">Eliminar espacio</div>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-lg-12">
                    <p>¿Está seguro de eliminar el espacio <b>{{ spaces.name }}</b>?</p>
                </div>
              </div>
            </div>
            <div class="card-action d-flex justify-content-end">
              <a href="{% url 'spaces_list' %}" class="btn btn-info">Cancelar</a>
              <button type="submit" class="btn btn-danger ms-2">Eliminar</button>    
            </div>
          </div>
        </div>
      </div>
    </div>
</form>
{% endblock %}

App/templates/spaces/edit.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/base.css' %}" />
{% endblock %}
{% block contenido %}
<form method="post" novalidate>
    {% csrf_token %}
    <div class="page-inner">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <div class="card-title">Editar Espacio</div>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="form-group form-inline">
                        <div class="row p-0">
                            <div class="col-12"> 
                              <div class="row">
                                <div class="col-md-6">
                                  <div class="form-group {% if form.name.errors %}has-error has-feedback{% endif %}">
                                    <span for="inlineinput" class="col-md-6 col-form-label">Nombre</span>
                                    {{ form.name }}
                                    <label>{{ form.name.errors }}</label>
                                  </div>
                                </div>
                                <div class="col-md-6">
                                  <div class="form-group {% if form.sport.errors %}has-error has-feedback{% endif %}">
                                    <span for="inlineinput" class="col-md-6 col-form-label">Deporte</span>
                                    {{ form.sport }}
                                    <label> {{ form.sport.errors }} </label>
                                  </div>  
                                </div>
                              </div>
                              <div class="row">
                                <div class="col-md-6">
                                  <div class="form-group {% if form.numberplayers.errors %}has-error has-feedback{% endif %}">
                                    <span for="inlineinput" class="col-md-6 col-form-label">Numero de jugadores permitidos</span>
                                    {{ form.numberplayers }}
                                    <label> {{ form.numberplayers.errors }} </label>
                                  </div> 
                                </div>
                                <div class="col-md-6">
                                  <div class="form-group {% if form.schedule.errors %}has-error has-feedback{% endif %}">
                                    <span for="inlineinput" class="col-md-6 col-form-label">Horario de juego</span>
                                    {{ form.schedule }}
                                    <label> {{ form.schedule.errors }} </label>
                                  </div>
                                </div>
                              </div>
                              <div class="form-group">
                                <span for="inlineinput" class="col-md-6 col-form-label">Descripcion</span>
                                {{ form.description }}
                                <label> {{ form.description.errors }} </label>
                              </div>
                            </div>
                        </div>
                      </div>
                </div>
              </div>
            </div>
            <div class="card-action d-flex justify-content-end">
              <a href="{% url 'spaces_list' %}" class="btn btn-danger">Cancelar</a>
              <button type="submit" class="btn btn-success ms-2">Guardar</button>
            </div>
          </div>
        </div>
      </div>
    </div>
</form>
{% endblock %}

App/templates/spaces/list.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
    <div class="page-inner">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <div class="row align-items-center">
                <div class="col-12 col-md-10">
                    <h4 class="card-title">Espacios</h4>
                </div>
                <div class="col-12 col-md-2 text-md-end text-center mt-2 mt-md-0">
                    <a href="{% url 'spaces_create' %}" class="btn btn-secondary">
                        <span class="btn-label">
                            <i class="fa fa-plus"></i>
                        </span>
                        Crear Espacio
                    </a>
                </div>
            </div>
        </div> 
          <div class="card-body">
            <div class="table-responsive">
              <table id="multi-filter-select" class="display table table-striped table-hover">
                <thead>
                  <tr>
                    <th class="text-center">Id</th>
                    <th class="text-center">Nombre</th>
                    <th class="text-center">Deporte</th>
                    <th class="text-center">Horario</th>
                    <th class="text-center">Numero de jugadores permitidos</th>
                    <th class="text-center">Descripcion</th>
                    <th class="text-center">Gestión</th>
                  </tr>
                </thead>
                <tbody>
                    {% for space in spaces %}
                  <tr>
                    <td class="text-center">{{ space.id }}</td>
                    <td class="text-center">{{ space.name }}</td>
                    <td class="text-center">{{ space.sport }}</td>
                    <td class="text-center">
                      {% if space.schedule.all %}
                          <ul class="list-unstyled mb-0">
                              {% for sch in space.schedule.all %}
                                  <li>
                                      {{ sch.get_day_display }}: 
                                      {{ sch.startime|time:"h:i A" }} - {{ sch.endtime|time:"h:i A" }}
                                  </li>
                                  <hr>
                              {% endfor %}
                          </ul>
                      {% else %}
                          No existen horarios
                      {% endif %}
                    </td>    
                    <td class="text-center">{{ space.numberplayers }}</td>
                    <td class="text-center">{{ space.description }}</td>
                    <td class="text-center">
                        <div class="d-flex justify-content-center gap-2">
                            <a href="{% url 'spaces_update' space.id %}" 
                               class="btn btn-icon btn-round btn-black btn-secondary"
                               data-bs-toggle="tooltip" 
                               data-bs-placement="top" 
                               title="Editar Espacio">
                                <i class="fa fa-edit"></i>
                            </a>
                            
                            <a href="{% url 'spaces_delete' space.id %}" 
                               class="btn btn-icon btn-round btn-black btn-danger"
                               data-bs-toggle="tooltip" 
                               data-bs-placement="top" 
                               title="Eliminar Espacio">
                                <i class="fa fa-trash"></i>
                            </a>
                        </div>
                    </td>                                      
                  </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
  </div>
{% endblock %}
{% block scripts %}
  <script src="{% static 'js/app/tools.js' %}"></script>
{% endblock %}