App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views.index import *
from .views.sport import *
from .views.schedules import *
from .views.company import *
from .views.spaces import *
from .views.reservation import *
from .views.users import *
from .views.roles import *
from .views.login import *
from .views.logs import *
from django.conf.urls import handler404
from django.contrib.auth import views as auth_views

handler404 = Custom404View.as_view()

urlpatterns = [
    #Login
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    #Home
    path('home/', CustomIndexView.as_view(), name="home"),
    #Sport
    path('sport/', ListSportView.as_view(), name="sport_list"),
    path('sport/create/', CreateSportView.as_view(), name="sport_create"),
    path('sport/update/<int:pk>/', UpdateSportView.as_view(), name="sport_update"),
    path('sport/delete/<int:pk>/', DeleteSportView.as_view(), name="sport_delete"),
    #Schedules
    path('schedules/', ListScheduleView.as_view(), name="schedules_list"),
    path('schedules/create/', CreateScheduleView.as_view(), name="schedules_create"),
    path('schedules/update/<int:pk>/', UpdateScheduleView.as_view(), name="schedules_update"),
    path('schedules/delete/<int:pk>/', DeleteScheduleView.as_view(), name="schedules_delete"),
    #Company
    path('company/create/', CreateCompanyView.as_view(), name="company_create"),
    path('company/update/<int:pk>/', UpdateCompanyView.as_view(), name="company_update"),
    #Spaces
    path('spaces/', ListSpacesView.as_view(), name="spaces_list"),
    path('spaces/create/', CreateSpacesView.as_view(), name="spaces_create"),
    path('spaces/update/<int:pk>/', UpdateSpacesView.as_view(), name="spaces_update"),
    path('spaces/delete/<int:pk>/', DeleteSpacesView.as_view(), name="spaces_delete"),
    path('spaces/ajax/<int:pk>/', AjaxSpacesByIdView.as_view(), name="spaces_ajax"),
    #Reservation
    path('reservation/', ListReservationView.as_view(), name="reservation_list"),
    path('calendar/', CalendarReservationView.as_view(), name="calendar"),
    path('reservations/', ReservationEventsView.as_view(), name="reservations_events"),
    path('reservation/create/', CreateReservationView.as_view(), name="reservation_create"),
    path('reservation/update/<int:pk>/', UpdateReservationView.as_view(), name="reservation_update"),
    path('reservation/delete/<int:pk>/', DeleteReservationView.as_view(), name="reservation_delete"),
    #Users
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('users/<int:pk>/permissions/', UserPermissionUpdateView.as_view(), name='user_permissions'),
    path('user/recover/password/', Recoverpassword.as_view(), name='recovery_password'),
    path('reset/<uidb64>/<token>/',CustomPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    #Roles
    path('roles/', RoleListView.as_view(), name='role_list'),
    path('roles/create/', RoleCreateView.as_view(), name='role_create'),
    path('roles/<int:pk>/update/', RoleUpdateView.as_view(), name='role_update'),
    path('roles/<int:pk>/delete/', RoleDeleteView.as_view(), name='role_delete'),
    #Logs
    path('logs/', LogsListView.as_view(), name='logs_list'),

]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

appZona3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

App/models.py
from django.db import models
from enum import Enum
from django.contrib.auth.models import Permission
from django.contrib.auth import get_user_model

User = get_user_model()

class Sport(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True, max_length=1000)

    class Meta:
        verbose_name = 'Sport'
        verbose_name_plural = 'Sports'
        db_table = 'sport'
        default_permissions = ()

    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=15)
    description = models.TextField(null=True, blank=True)
    logo = models.ImageField(upload_to='company_logo/', null=True, blank=True)

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'
        db_table = 'company'
        default_permissions = ()

    def __str__(self):
        return self.name

class Days(Enum):
    LUNES = 1
    MARTES = 2
    MIERCOLES = 3
    JUEVES = 4
    VIERNES = 5
    SABADO = 6
    DOMINGO = 7

    @classmethod
    def choices(cls):
        return [(tag.value, tag.name.capitalize()) for tag in cls]

class Schedule(models.Model):
    day = models.IntegerField(choices=Days.choices(), default=Days.LUNES.value)
    startime = models.TimeField()
    endtime = models.TimeField()

    class Meta:
        verbose_name = 'Schedule'
        verbose_name_plural = 'Schedules'
        db_table = 'schedules'
        default_permissions = ()

    def __str__(self):
        return f"{Days(self.day).name} ({self.startime} - {self.endtime})"

    @property
    def day_name(self):
        return Days(self.day).name.capitalize()

    
class Spaces(models.Model):
    name = models.CharField(max_length=50)
    sport = models.ForeignKey(Sport, on_delete=models.PROTECT)
    description = models.TextField(null=True, blank=True)
    schedule = models.ManyToManyField(Schedule, blank=True)
    numberplayers = models.IntegerField()

    class Meta:
        verbose_name = 'Space'
        verbose_name_plural = 'Spaces'
        db_table = 'spaces'
        default_permissions = ()

    def __str__(self):
        return self.name

class Reservation(models.Model):
    client_name = models.CharField(max_length=50)
    client_cell = models.CharField(max_length=15)
    client_email = models.EmailField()
    space = models.ForeignKey(Spaces, on_delete=models.PROTECT)
    reservation_start = models.DateTimeField()
    reservation_end = models.DateTimeField()

    class Meta:
        verbose_name = 'Reservation'
        verbose_name_plural = 'Reservations'
        db_table = 'reservation'
        default_permissions = ()

    def __str__(self):
        return self.client_name

class Module(models.Model):
    name = models.CharField(max_length=100, unique=True)
    icon = models.CharField(max_length=50)
    permissions = models.ManyToManyField(Permission, related_name='modules')
    url_name = models.CharField(max_length=100) 

    class Meta:
        default_permissions = ()

    def __str__(self):
        return self.name

    def user_has_access(self, user):
        return user.user_permissions.filter(id__in=self.permissions.values_list('id', flat=True)).exists()



class Log(models.Model):
    ACTION_CHOICES = [
        ('create', 'Create'),
        ('update', 'Update'),
        ('delete', 'Delete'),
    ]

    module = models.CharField(max_length=255)  
    date = models.DateTimeField(auto_now_add=True)  
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)  
    description = models.TextField()  
    action = models.CharField(max_length=10, choices=ACTION_CHOICES) 

    def __str__(self):
        return f"{self.module} - {self.action} - {self.date.strftime('%Y-%m-%d %H:%M:%S')}"

App/templates/base.html
{% load static %}
<html lang="es">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Zona 3x3</title>
    <meta
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
      name="viewport"
    />
    <link
      rel="icon"
      href="{% static 'img/kaiadmin/favicon.ico' %}"
      type="image/x-icon"
    />

    <!-- Fonts and icons -->
    <script src="{% static 'js/plugin/webfont/webfont.min.js' %}"></script>
    <script>
      WebFont.load({
        google: { families: ["Public Sans:300,400,500,600,700"] },
        custom: {
          families: [
            "Font Awesome 5 Solid",
            "Font Awesome 5 Regular",
            "Font Awesome 5 Brands",
            "simple-line-icons",
          ],
          urls: ["{% static 'css/fonts.min.css' %}"],
        },
        active: function () {
          sessionStorage.fonts = true;
        },
      });
    </script>
    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/plugins.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/kaiadmin.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}" />
    <!-- Flatpickr CSS -->
    <link rel="stylesheet" href="{% static 'css/flatpickr.min.css' %}"/>

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="{% static 'css/demo.css' %}" />
    {% block styles %}

    {% endblock %}
  </head>
  <body>
    <div class="wrapper">
      <!-- Sidebar -->
      <div class="sidebar" data-background-color="dark">
        <div class="sidebar-logo">
          <!-- Logo Header -->
          <div class="logo-header d-flex justify-content-center" data-background-color="dark">
            <a href="{% url 'home' %}" class="logo">
              {% if company.logo %}
                  <img src="{{ company.logo.url }}" alt="navbar brand" class="navbar-brand" height="70" width="90" />
              {% else %}
                  <i class="fas fa-home fa-3x"></i> 
              {% endif %}
            </a>
            <div class="nav-toggle">
              <button class="btn btn-toggle toggle-sidebar">
                <i class="gg-menu-right"></i>
              </button>
              <button class="btn btn-toggle sidenav-toggler">
                <i class="gg-menu-left"></i>
              </button>
            </div>
            <button class="topbar-toggler more">
              <i class="gg-more-vertical-alt"></i>
            </button>
          </div>
          <!-- End Logo Header -->
        </div>
        <div class="sidebar-wrapper scrollbar scrollbar-inner">
          <div class="sidebar-content">
            <ul class="nav nav-secondary">
              <li class="nav-item active">
                <a href="{% url 'home' %}" class="fas fa-home">
                  <i class="fas fa-home"></i><p>{{ company.name | default:"Inicio" }}</p>
                </a>
              </li>
              <li class="nav-section">
                <span class="sidebar-mini-icon">
                  <i class="fa fa-ellipsis-h"></i>
                </span>
                <h4 class="text-section">Opciones</h4>
              </li>
              {% for module in modules %}
                <li class="nav-item">
                  <a href="{% url module.url_name %}">
                    <i class="{{ module.icon }}"></i>
                    <p>{{ module.name }}</p>
                  </a>
                </li>
              {% empty %}
                <li class="nav-item text-center">
                  <i class="fas fa-exclamation-triangle"></i>
                  <p>No tienes acceso a ningún módulo.</p>
                </li>
              {% endfor %}

            
            </ul>
          </div>
        </div>
      </div>
      <!-- End Sidebar -->

      <div class="main-panel">
        <div class="main-header">
          <div class="main-header-logo">
            <!-- Logo Header -->
            <div class="logo-header" data-background-color="dark">
              <a href="index.html" class="logo">
                <img
                  src="{% static 'img/kaiadmin/logo_light.svg' %}"
                  alt="navbar brand"
                  class="navbar-brand"
                  height="20"
                />
              </a>
              <div class="nav-toggle">
                <button class="btn btn-toggle toggle-sidebar">
                  <i class="gg-menu-right"></i>
                </button>
                <button class="btn btn-toggle sidenav-toggler">
                  <i class="gg-menu-left"></i>
                </button>
              </div>
              <button class="topbar-toggler more">
                <i class="gg-more-vertical-alt"></i>
              </button>
            </div>
            <!-- End Logo Header -->
          </div>
          <!-- Navbar Header -->
          <nav
            class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom"
          >
            <div class="container-fluid">
              <nav class="navbar navbar-header-left navbar-expand-lg navbar-form nav-search p-0 d-none d-lg-flex"></nav>
              <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
                <li class="nav-item topbar-user dropdown hidden-caret">
                  <a
                    class="dropdown-toggle profile-pic"
                    data-bs-toggle="dropdown"
                    href="#"
                    aria-expanded="false"
                  >
                    <div class="avatar-sm">
                      <img
                        src="{% static 'img/logoPerfil.png' %}"
                        alt="..."
                        class="avatar-img rounded-circle"
                      />
                    </div>
                    <span class="profile-username">
                      <span class="op-7">Hola,</span>
                      <span class="fw-bold">{{ request.user }}</span>
                    </span>
                  </a>
                  <ul class="dropdown-menu dropdown-user animated fadeIn">
                    <div class="dropdown-user-scroll scrollbar-outer">
                      <li>
                        <div class="user-box">
                          <div class="avatar-lg">
                            <img
                              src="{% static 'img/logoPerfil.png' %}"
                              alt="image profile"
                              class="avatar-img rounded"
                            />
                          </div>
                          <div class="u-text">
                            <h4>{{ request.user }}</h4>
                            <p class="text-muted">{{ request.user.email }}</p>
                          </div>
                        </div>
                      </li>
                      <li>
                        <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                      </li>
                    </div>
                  </ul>
                </li>
              </ul>
            </div>
          </nav>
          <!-- End Navbar -->
        </div>

    <div class="container">

        {% block contenido %}

        {% endblock %}

    </div>
        <footer class="footer">
          <div class="container-fluid d-flex justify-content-between">
            <nav class="pull-left">
            <div class="copyright">
              2025, made with <i class="fa fa-heart heart text-danger"></i> by
              <a href="">Guarida app</a>
            </div>
          </div>
        </footer>
      </div>
    </div>
    <!--   Core JS Files   -->
    <script src="{% static 'js/core/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/core/popper.min.js' %}"></script>
    <script src="{% static 'js/core/bootstrap.min.js' %}"></script>

    <!-- jQuery Scrollbar -->
    <script src="{% static 'js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>

    <!-- Chart JS -->
    <script src="{% static 'js/plugin/chart.js/chart.min.js' %}"></script>

    <!-- jQuery Sparkline -->
    <script src="{% static 'js/plugin/jquery.sparkline/jquery.sparkline.min.js' %}"></script>

    <!-- Chart Circle -->
    <script src="{% static 'js/plugin/chart-circle/circles.min.js' %}"></script>

    <!-- Datatables -->
    <script src="{% static 'js/plugin/datatables/datatables.min.js' %}"></script>

    <!-- Bootstrap Notify -->
    <script src="{% static 'js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script>

    <!-- jQuery Vector Maps -->
    <script src="{% static 'js/plugin/jsvectormap/jsvectormap.min.js' %}"></script>
    <script src="{% static 'js/plugin/jsvectormap/world.js' %}"></script>

    <!-- Sweet Alert -->
    <script src="{% static 'js/plugin/sweetalert/sweetalert.min.js' %}"></script>

    <!-- Kaiadmin JS -->
    <script src="{% static 'js/kaiadmin.min.js' %}"></script>

    <!-- Kaiadmin DEMO methods, don't include it in your project! -->
    <script src="{% static 'js/setting-demo.js' %}"></script>
    <script src="{% static 'js/demo.js' %}"></script>
    <script src="{% static 'js/plugin/select2/select2.min.js' %}"></script>
    <script>
      $(document).ready(function() {
          $('.style-select2').select2();
      });
    </script>

    <!-- Flatpickr JS -->
    <script src="{% static 'js/plugin/flatpickr.min.js' %}"></script>
    {% include "messages.html" %}
    {% block scripts %}

    {% endblock %}
  </body>
</html>

App/templates/base_email_template.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ subject }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
        }

        .email-container {
            width: 100%;
            background-color: #ffffff;
            max-width: 600px;
            margin: 0 auto;
            border: 1px solid #ddd;
            border-radius: 8px;
            overflow: hidden;
        }

        .email-header {
            background-color: #6861ce;
            padding: 20px;
            text-align: center;
        }

        .email-header h1 {
            color: #fff;
            font-size: 24px;
            margin: 0;
        }

        .email-body {
            padding: 20px;
        }

        .email-body p {
            font-size: 16px;
            line-height: 1.6;
            color: #333;
        }

        .button-wrapper {
            text-align: center;
            margin-top: 20px;
        }

        .button {
            display: inline-block;
            background-color: #6861ce !important;
            color: #fff !important;
            text-align: center;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
        }

        .footer {
            text-align: center;
            font-size: 12px;
            color: #777;
            margin-top: 30px;
            padding: 20px;
        }

        .footer a {
            color: #6861ce !important;
            text-decoration: none;
        }
    </style>
</head>
<body>

    <div class="email-container">
        <div class="email-header">
            <h1>{{ subject }}</h1>
        </div>

        <div class="email-body">
            <p>{{ body|safe }}</p>

            {% if button_url %}
            <div class="button-wrapper">
                <a href="{{ button_url }}" class="button">
                    {{ button_text }}
                </a>
            </div>
            {% endif %}
        </div>

        <div class="footer">
            <p>Si no solicitaste este registro, por favor ignora este correo.</p>
        </div>
    </div>

</body>
</html>

App/templates/index.html
{% extends "base.html" %}
{% block contenido %}
    <div class="page-inner">
      <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row pt-2 pb-4">
        <div>
          <h1 class="fw-bold mb-3">
            <b>{{ company.name|default:'Nombre de la empresa' }}</b>
          </h1>        
        </div>
        <div class="ms-md-auto py-2 py-md-0">
          {% if perms.App.add_company %}
            {% if company %}
              <a href="{% url 'company_update' company.pk %}" class="btn btn-secondary btn-round">Editar empresa</a>
            {% else %}
              <a href="{% url 'company_create' %}" class="btn btn-primary btn-round">Crear empresa</a>
            {% endif %}
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6 col-md-3">
          <div class="card card-stats card-round">
            <div class="card-body">
              <div class="row align-items-center">
                <div class="col-icon">
                  <div
                    class="icon-big text-center icon-primary bubble-shadow-small"
                  >
                    <i class="fas fa-users"></i>
                  </div>
                </div>
                <div class="col col-stats ms-3 ms-sm-0">
                  <div class="numbers">
                    <p class="card-category">Visitantes</p>
                    <h4 class="card-title">1,294</h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-3">
          <div class="card card-stats card-round">
            <div class="card-body">
              <div class="row align-items-center">
                <div class="col-icon">
                  <div
                    class="icon-big text-center icon-info bubble-shadow-small"
                  >
                    <i class="fas fa-user-check"></i>
                  </div>
                </div>
                <div class="col col-stats ms-3 ms-sm-0">
                  <div class="numbers">
                    <p class="card-category">Clientes</p>
                    <h4 class="card-title">1303</h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-3">
          <div class="card card-stats card-round">
            <div class="card-body">
              <div class="row align-items-center">
                <div class="col-icon">
                  <div
                    class="icon-big text-center icon-success bubble-shadow-small"
                  >
                    <i class="fas fa-luggage-cart"></i>
                  </div>
                </div>
                <div class="col col-stats ms-3 ms-sm-0">
                  <div class="numbers">
                    <p class="card-category">Total del dia de hoy</p>
                    <h4 class="card-title">$ 1,345</h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-3">
          <div class="card card-stats card-round">
            <div class="card-body">
              <div class="row align-items-center">
                <div class="col-icon">
                  <div
                    class="icon-big text-center icon-secondary bubble-shadow-small"
                  >
                    <i class="far fa-check-circle"></i>
                  </div>
                </div>
                <div class="col col-stats ms-3 ms-sm-0">
                  <div class="numbers">
                    <p class="card-category">Reservas de hoy</p>
                    <h4 class="card-title">576</h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">RESERVAS</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table id="multi-filter-select" class="display table table-striped table-hover">
                <thead>
                  <tr>
                    <th>Cliente</th>
                    <th>Telefono</th>
                    <th>Cancha</th>
                    <th>Fecha de la reserva</th>
                    <th>Pago pendiente</th>
                    <th></th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>Cliente</th>
                    <th>Telefono</th>
                    <th>Cancha</th>
                    <th>Fecha de la reserva</th>
                    <th>Pago pendiente</th>
                    <th></th>
                  </tr>
                </tfoot>
                <tbody>
                  <tr>
                    <td>Tiger Nixon</td>
                    <td>System Architect</td>
                    <td>Edinburgh</td>
                    <td>2011/04/25</td>
                    <td>$0</td>
                    <td data-value="1">
                      <i class="fas fa-check-circle" style="color: green; font-size: 2.0em;"></i>
                    </td>
                  </tr>
                  <tr>
                    <td>Garrett Winters</td>
                    <td>Accountant</td>
                    <td>Tokyo</td>
                    <td>2011/07/25</td>
                    <td>$80.000</td>
                    <th><i class="fas fa-times-circle" style="color: red; font-size: 2.0em;"></i></th>
                  </tr>
                  <tr>
                    <td>Ashton Cox</td>
                    <td>Junior Technical Author</td>
                    <td>San Francisco</td>
                    <td>2009/01/12</td>
                    <td>$100.000</td>
                    <th><i class="fas fa-times-circle" style="color: red; font-size: 2.0em;"></i></th>
                  </tr>
                  <tr>
                    <td>Cedric Kelly</td>
                    <td>Senior Javascript Developer</td>
                    <td>Edinburgh</td>
                    <td>2012/03/29</td>
                    <td>$0</td>
                    <td data-value="1">
                      <i class="fas fa-check-circle" style="color: green; font-size: 2.0em;"></i>
                    </td>
                  </tr>
                  <tr>
                    <td>Airi Satou</td>
                    <td>Accountant</td>
                    <td>Tokyo</td>
                    <td>2008/11/28</td>
                    <td>$0</td>
                    <td><i class="fas fa-check-circle" style="color: green; font-size: 2.0em;"></i></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
  </div>
{% endblock %}
{% block scripts %}
<script>
    $("#lineChart").sparkline([102, 109, 120, 99, 110, 105, 115], {
      type: "line",
      height: "70",
      width: "100%",
      lineWidth: "2",
      lineColor: "#177dff",
      fillColor: "rgba(23, 125, 255, 0.14)",
    });

    $("#lineChart2").sparkline([99, 125, 122, 105, 110, 124, 115], {
      type: "line",
      height: "70",
      width: "100%",
      lineWidth: "2",
      lineColor: "#f3545d",
      fillColor: "rgba(243, 84, 93, .14)",
    });

    $("#lineChart3").sparkline([105, 103, 123, 100, 95, 105, 115], {
      type: "line",
      height: "70",
      width: "100%",
      lineWidth: "2",
      lineColor: "#ffa534",
      fillColor: "rgba(255, 165, 52, .14)",
    });

    $("#multi-filter-select").DataTable({
        pageLength: 5,
        initComplete: function () {
          this.api()
            .columns()
            .every(function () {
              var column = this;
              var select = $(
                '<select class="form-select"><option value=""></option></select>'
              )
                .appendTo($(column.footer()).empty())
                .on("change", function () {
                  var val = $.fn.dataTable.util.escapeRegex($(this).val());

                  column
                    .search(val ? "^" + val + "$" : "", true, false)
                    .draw();
                });

              column
                .data()
                .unique()
                .sort()
                .each(function (d, j) {
                  select.append(
                    '<option value="' + d + '">' + d + "</option>"
                  );
                });
            });
        },
      });
  </script>
{% endblock %}

App/templates/messages.html
{% if messages %}
  {% for message in messages %}
  <script>
    var content = {};
    var type_error = "{{ message.tags }}";
    content.message = '';
    content.title = "{{ message }}";
    
    if (type_error == 'success') {
      content.icon = "icon-check";
    } else if (type_error == 'error') {
      content.icon = "icon-close"; 
      type_error = 'danger';
    } else if (type_error == 'warning') {
      content.icon = "icon-energy";    
    } else if (type_error == 'info') {
      content.icon = "icon-info";    
    }
    
    $.notify(content, {
      type: type_error,
      placement: {
        from: 'top',
        align: 'right',
      },
      time: 1,
      delay: 1500,
      animate: {
        enter: 'animated fadeInDown',
        exit: 'animated fadeOutUp'
      }
    });
  </script>
  {% endfor %}
{% endif %}

App/templates/producto.html
{% extends "base.html" %}
{% block contenido %}
<h1 class="fw-bold mb-3"><b>Producto</b></h1>
{% endblock %}